# Dockerfile.daemon
FROM php:8.2-cli

# Cài extensions cần thiết
RUN apt-get update && apt-get install -y \
    libpng-dev libjpeg-dev libonig-dev libxml2-dev zip unzip git libzip-dev mariadb-client \
    && docker-php-ext-install pdo_mysql mysqli gd zip

# Copy source code
COPY ./src /var/www/html/

WORKDIR /var/www/html

# Quyền
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Run daemon script
CMD ["php", "cron.php"]
