services:
  - type: web
    name: espocrm
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""  # Không cần nếu Dockerfile lo hết rồi
    startCommand: ""  # Dùng CMD trong Dockerfile
    plan: free
    envVars:
      - key: ESPOCRM_DATABASE_HOST
        value: postgresql://espocrm:rcWzk5XYokO8SxvNuuqqNvWY6HPS8ViH@dpg-d0kcj0t6ubrc73b6ehs0-a/espocrm_mkpn
      - key: ESPOCRM_DATABASE_USER
        value: espocrm
      - key: ESPOCRM_DATABASE_PASSWORD
        value: rcWzk5XYokO8SxvNuuqqNvWY6HPS8ViH
      - key: ESPOCRM_DATABASE_NAME
        value: espocrm_mkpn
      - key: ESPOCRM_DATABASE_PORT
        value: 5432

  - type: private-service
    name: espocrm-daemon
    env: docker
    dockerfilePath: ./Dockerfile.daemon
    plan: free

  - type: private-service
    name: espocrm-websocket
    env: docker
    dockerfilePath: ./Dockerfile.websocket
    plan: free

  - type: private-service
    name: espocrm-db
    env: docker
    image: mariadb:latest
    plan: free
    envVars:
      - key: MARIADB_ROOT_PASSWORD
        value: root_password
      - key: MARIADB_DATABASE
        value: espocrm
      - key: MARIADB_USER
        value: espocrm
      - key: MARIADB_PASSWORD
        value: database_password
    disk:
      name: espocrm-db-data
      mountPath: /var/lib/mysql
      sizeGB: 1
